// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using repositories.Dbcontext;

#nullable disable

namespace repositories.Migrations
{
    [DbContext(typeof(MathLpContext))]
    partial class MathLpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("repositories.Models.AiRequest", b =>
                {
                    b.Property<int>("AIRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AIRequestId"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestType")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AIRequestId");

                    b.HasIndex("LevelId");

                    b.HasIndex("UserId");

                    b.ToTable("AiRequest");

                    b.HasData(
                        new
                        {
                            AIRequestId = 1,
                            Cost = 1.5m,
                            CreatedAt = new DateTime(2024, 6, 14, 8, 51, 0, 0, DateTimeKind.Utc),
                            LevelId = 2,
                            Prompt = "Generate a lesson plan for algebra.",
                            RequestType = 0,
                            Response = "Lesson plan generated.",
                            Status = 1,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("repositories.Models.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerId"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("answers");

                    b.HasData(
                        new
                        {
                            AnswerId = 1,
                            AnswerText = "2",
                            IsCorrect = true,
                            QuestionId = 1
                        },
                        new
                        {
                            AnswerId = 2,
                            AnswerText = "4",
                            IsCorrect = false,
                            QuestionId = 1
                        });
                });

            modelBuilder.Entity("repositories.Models.Attachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LessonDetailId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadTimestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("AttachmentId");

                    b.HasIndex("LessonDetailId");

                    b.ToTable("attachments");

                    b.HasData(
                        new
                        {
                            AttachmentId = 1,
                            FileName = "intro.pdf",
                            FilePath = "/files/intro.pdf",
                            FileSize = 102400L,
                            FileType = "pdf",
                            LessonDetailId = 1,
                            UploadTimestamp = new DateTime(2024, 6, 14, 8, 51, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("repositories.Models.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("auditLogs");

                    b.HasData(
                        new
                        {
                            LogId = 1,
                            Action = 0,
                            Details = "Created lesson plan.",
                            EntityId = 1,
                            EntityName = "LessonPlan",
                            Timestamp = new DateTime(2024, 6, 14, 8, 51, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("repositories.Models.Difficulty", b =>
                {
                    b.Property<int>("DifficultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DifficultyId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("DifficultyId");

                    b.ToTable("difficulties");

                    b.HasData(
                        new
                        {
                            DifficultyId = 1,
                            Description = "Basic level",
                            Name = "Easy",
                            Value = 1
                        },
                        new
                        {
                            DifficultyId = 2,
                            Description = "Intermediate level",
                            Name = "Medium",
                            Value = 2
                        },
                        new
                        {
                            DifficultyId = 3,
                            Description = "Advanced level",
                            Name = "Hard",
                            Value = 3
                        });
                });

            modelBuilder.Entity("repositories.Models.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessonId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsShared")
                        .HasColumnType("bit");

                    b.Property<int>("LessonPlanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("LessonId");

                    b.HasIndex("LessonPlanId");

                    b.ToTable("lessons");

                    b.HasData(
                        new
                        {
                            LessonId = 1,
                            Content = "Algebra is ...",
                            IsShared = true,
                            LessonPlanId = 1,
                            PublishedDate = new DateTime(2024, 6, 14, 8, 51, 0, 0, DateTimeKind.Utc),
                            Title = "What is Algebra?"
                        });
                });

            modelBuilder.Entity("repositories.Models.LessonDetail", b =>
                {
                    b.Property<int>("LessonDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessonDetailId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentLaTeX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContentType")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("LessonDetailId");

                    b.HasIndex("LessonId");

                    b.ToTable("lessonDetails");

                    b.HasData(
                        new
                        {
                            LessonDetailId = 1,
                            Content = "Algebra is a branch of mathematics ...",
                            ContentType = 0,
                            CreatedAt = new DateTime(2024, 6, 14, 8, 51, 0, 0, DateTimeKind.Utc),
                            LessonId = 1,
                            Order = 1
                        });
                });

            modelBuilder.Entity("repositories.Models.LessonPlan", b =>
                {
                    b.Property<int>("LessonPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessonPlanId"));

                    b.Property<int?>("AiRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("ExportPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("LessonPlanId");

                    b.HasIndex("AiRequestId");

                    b.HasIndex("LevelId");

                    b.HasIndex("TeacherId");

                    b.ToTable("lessonPlans");

                    b.HasData(
                        new
                        {
                            LessonPlanId = 1,
                            AiRequestId = 1,
                            Content = "Introduction to Algebra",
                            CreatedAt = new DateTime(2024, 6, 14, 8, 51, 0, 0, DateTimeKind.Utc),
                            Duration = 60,
                            LevelId = 2,
                            Status = 1,
                            TeacherId = 2,
                            Title = "Algebra Basics",
                            Version = 1
                        });
                });

            modelBuilder.Entity("repositories.Models.Level", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelId"));

                    b.Property<int>("EducationLevel")
                        .HasColumnType("int");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("LevelId");

                    b.ToTable("levels");

                    b.HasData(
                        new
                        {
                            LevelId = 1,
                            EducationLevel = 0,
                            LevelName = "Primary School",
                            Order = 1
                        },
                        new
                        {
                            LevelId = 2,
                            EducationLevel = 1,
                            LevelName = "Secondary School",
                            Order = 2
                        },
                        new
                        {
                            LevelId = 3,
                            EducationLevel = 2,
                            LevelName = "High School",
                            Order = 3
                        });
                });

            modelBuilder.Entity("repositories.Models.Progress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgressId"));

                    b.Property<DateTime?>("AttemptDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompletionStatus")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("ProgressId");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.ToTable("progresses");

                    b.HasData(
                        new
                        {
                            ProgressId = 1,
                            AttemptDate = new DateTime(2024, 6, 14, 8, 51, 0, 0, DateTimeKind.Utc),
                            CompletionStatus = 2,
                            IsActive = true,
                            LessonId = 1,
                            StudentId = 1
                        });
                });

            modelBuilder.Entity("repositories.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<int?>("AiRequestId")
                        .HasColumnType("int");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DifficultyId")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAIGenerated")
                        .HasColumnType("bit");

                    b.Property<int?>("QuestionBankId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionType")
                        .HasColumnType("int");

                    b.Property<int?>("QuizId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Topic")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("QuestionId");

                    b.HasIndex("AiRequestId");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("QuestionBankId");

                    b.HasIndex("QuizId");

                    b.ToTable("questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            AiRequestId = 1,
                            CorrectAnswer = "2",
                            CreatedAt = new DateTime(2024, 6, 14, 8, 51, 0, 0, DateTimeKind.Utc),
                            DifficultyId = 1,
                            Explanation = "Divide both sides by 2.",
                            IsAIGenerated = false,
                            QuestionBankId = 1,
                            QuestionText = "What is x in 2x=4?",
                            QuestionType = 0,
                            QuizId = 1,
                            Status = 1,
                            Tags = "algebra,equation",
                            Topic = 3
                        });
                });

            modelBuilder.Entity("repositories.Models.QuestionBank", b =>
                {
                    b.Property<int>("QuestionBankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionBankId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("QuestionBankId");

                    b.HasIndex("LevelId");

                    b.HasIndex("TeacherId");

                    b.ToTable("questionBanks");

                    b.HasData(
                        new
                        {
                            QuestionBankId = 1,
                            Description = "Basic algebra questions",
                            IsPublic = true,
                            LevelId = 2,
                            Name = "Algebra Questions",
                            TeacherId = 2
                        });
                });

            modelBuilder.Entity("repositories.Models.Quiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizId"));

                    b.Property<int>("AttemptLimit")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAIGenerated")
                        .HasColumnType("bit");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.HasKey("QuizId");

                    b.HasIndex("LevelId");

                    b.HasIndex("TeacherId");

                    b.ToTable("quizzes");

                    b.HasData(
                        new
                        {
                            QuizId = 1,
                            AttemptLimit = 3,
                            CreatedAt = new DateTime(2024, 6, 14, 8, 51, 0, 0, DateTimeKind.Utc),
                            IsAIGenerated = false,
                            LevelId = 2,
                            Status = 1,
                            TeacherId = 2,
                            TimeLimit = 30,
                            Title = "Algebra Quiz",
                            TotalScore = 100
                        });
                });

            modelBuilder.Entity("repositories.Models.Submission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<int>("DurationTaken")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SubmissionId");

                    b.HasIndex("QuizId");

                    b.HasIndex("StudentId");

                    b.ToTable("submissions");

                    b.HasData(
                        new
                        {
                            SubmissionId = 1,
                            AttemptNumber = 1,
                            DurationTaken = 1200,
                            Feedback = "Great job!",
                            QuizId = 1,
                            Score = 100m,
                            Status = 0,
                            StudentId = 1,
                            SubmittedAt = new DateTime(2024, 6, 14, 8, 51, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("repositories.Models.SubmissionDetail", b =>
                {
                    b.Property<int>("SubmissionDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionDetailId"));

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<decimal>("ScoreEarned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StudentAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.HasKey("SubmissionDetailId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("submissionDetails");

                    b.HasData(
                        new
                        {
                            SubmissionDetailId = 1,
                            Explanation = "Correct answer.",
                            IsCorrect = true,
                            QuestionId = 1,
                            ScoreEarned = 100m,
                            StudentAnswer = "2",
                            SubmissionId = 1
                        });
                });

            modelBuilder.Entity("repositories.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GradeLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("LevelId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 6, 14, 8, 51, 0, 0, DateTimeKind.Utc),
                            Credit = 0m,
                            Email = "student1@example.com",
                            IsActive = true,
                            LevelId = 1,
                            Password = "hashedpassword",
                            Role = 0,
                            Username = "student1"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2024, 6, 14, 8, 51, 0, 0, DateTimeKind.Utc),
                            Credit = 100m,
                            Email = "teacher1@example.com",
                            IsActive = true,
                            LevelId = 2,
                            Password = "hashedpassword",
                            Role = 1,
                            Username = "teacher1"
                        });
                });

            modelBuilder.Entity("repositories.Models.AiRequest", b =>
                {
                    b.HasOne("repositories.Models.Level", "Level")
                        .WithMany("AiRequests")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("repositories.Models.User", "User")
                        .WithMany("AiRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("User");
                });

            modelBuilder.Entity("repositories.Models.Answer", b =>
                {
                    b.HasOne("repositories.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("repositories.Models.Attachment", b =>
                {
                    b.HasOne("repositories.Models.LessonDetail", "LessonDetail")
                        .WithMany("Attachments")
                        .HasForeignKey("LessonDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonDetail");
                });

            modelBuilder.Entity("repositories.Models.AuditLog", b =>
                {
                    b.HasOne("repositories.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("repositories.Models.Lesson", b =>
                {
                    b.HasOne("repositories.Models.LessonPlan", "LessonPlan")
                        .WithMany("Lessons")
                        .HasForeignKey("LessonPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonPlan");
                });

            modelBuilder.Entity("repositories.Models.LessonDetail", b =>
                {
                    b.HasOne("repositories.Models.Lesson", "Lesson")
                        .WithMany("LessonDetails")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("repositories.Models.LessonPlan", b =>
                {
                    b.HasOne("repositories.Models.AiRequest", "AiRequest")
                        .WithMany("LessonPlans")
                        .HasForeignKey("AiRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("repositories.Models.Level", "Level")
                        .WithMany("LessonPlans")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("repositories.Models.User", "Teacher")
                        .WithMany("LessonPlans")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiRequest");

                    b.Navigation("Level");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("repositories.Models.Progress", b =>
                {
                    b.HasOne("repositories.Models.Lesson", "Lesson")
                        .WithMany("Progresses")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("repositories.Models.User", "Student")
                        .WithMany("Progresses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("repositories.Models.Question", b =>
                {
                    b.HasOne("repositories.Models.AiRequest", "AiRequest")
                        .WithMany("Questions")
                        .HasForeignKey("AiRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("repositories.Models.Difficulty", "Difficulty")
                        .WithMany("Questions")
                        .HasForeignKey("DifficultyId");

                    b.HasOne("repositories.Models.QuestionBank", "QuestionBank")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionBankId");

                    b.HasOne("repositories.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId");

                    b.Navigation("AiRequest");

                    b.Navigation("Difficulty");

                    b.Navigation("QuestionBank");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("repositories.Models.QuestionBank", b =>
                {
                    b.HasOne("repositories.Models.Level", "Level")
                        .WithMany("QuestionBanks")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("repositories.Models.User", "Teacher")
                        .WithMany("QuestionBanks")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("repositories.Models.Quiz", b =>
                {
                    b.HasOne("repositories.Models.Level", "Level")
                        .WithMany("Quizzes")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("repositories.Models.User", "Teacher")
                        .WithMany("Quizzes")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("repositories.Models.Submission", b =>
                {
                    b.HasOne("repositories.Models.Quiz", "Quiz")
                        .WithMany("Submissions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("repositories.Models.User", "Student")
                        .WithMany("Submissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("repositories.Models.SubmissionDetail", b =>
                {
                    b.HasOne("repositories.Models.Question", "Question")
                        .WithMany("SubmissionDetails")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("repositories.Models.Submission", "Submission")
                        .WithMany("SubmissionDetails")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("repositories.Models.User", b =>
                {
                    b.HasOne("repositories.Models.Level", "Level")
                        .WithMany("Users")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("repositories.Models.AiRequest", b =>
                {
                    b.Navigation("LessonPlans");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("repositories.Models.Difficulty", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("repositories.Models.Lesson", b =>
                {
                    b.Navigation("LessonDetails");

                    b.Navigation("Progresses");
                });

            modelBuilder.Entity("repositories.Models.LessonDetail", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("repositories.Models.LessonPlan", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("repositories.Models.Level", b =>
                {
                    b.Navigation("AiRequests");

                    b.Navigation("LessonPlans");

                    b.Navigation("QuestionBanks");

                    b.Navigation("Quizzes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("repositories.Models.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("SubmissionDetails");
                });

            modelBuilder.Entity("repositories.Models.QuestionBank", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("repositories.Models.Quiz", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("repositories.Models.Submission", b =>
                {
                    b.Navigation("SubmissionDetails");
                });

            modelBuilder.Entity("repositories.Models.User", b =>
                {
                    b.Navigation("AiRequests");

                    b.Navigation("AuditLogs");

                    b.Navigation("LessonPlans");

                    b.Navigation("Progresses");

                    b.Navigation("QuestionBanks");

                    b.Navigation("Quizzes");

                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
